### ISSUE TITLE
Wrong Import in VRCore.js

### ISSUE THREAD

**Issue by cowonacid** [YoneChen/webvr-webpack-boilerplate#3]
Thank you for this great boilerplate! I will give it a try in my current vr project :)
In the following file there is a small typing mistake: 
src/common/js/VRCore.js

The Line:   "import 'three-onEvent';"
has to be   "import 'three-onevent';"

After that change everything works great :+1:

**Comment by YoneChen** [comment]
Fixed👌~ Thank you!
